---
# - name: Ensure for docker installed on servers
#   hosts: all
#   become: yes
#   remote_user: ubuntu
#   become_user: root
#   roles:
#     - role: common

- name: Ensure builserver is prepared
  hosts: build
  become: yes
  remote_user: ubuntu
  become_user: root
  roles:
    - role: prepare_build_server
      vars:
        dockerhub_username: "{{ lookup('env','DOCKERHUB_CREDS_USR') }}"
        dockerhub_token: "{{ lookup('env','DOCKERHUB_CREDS_PSW') }}"

- name: Ensure webserver is prepared
  hosts: web
  become: yes
  remote_user: ubuntu
  become_user: root
  roles:
    - role: prepare_web_server
...