---
- name: Create aws hosts
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  roles:
    - role: runvm

- name: Build prod docker image
  hosts: build
  become: yes
  become_user: root
  roles:
    - role: common
    - role: build_webserver
      vars:
        source_repository_url: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        build_server_name: buildingserver1
        build_server_version: 0.1
        dockerhub_username: 'artempvl'
        dockerhub_token: 'cfb00c0f-3097-42d7-b18d-984f27200c5e'
        webserver_image_name: webserver1
        webserver_version: 0.0.1

- name: Run web server
  hosts: web
  become: yes
  become_user: root
  roles:
    - role: webserver
      vars:
        webserver_port: 80
        dockerhub_username: 'artempvl'
        dockerhub_token: 'cfb00c0f-3097-42d7-b18d-984f27200c5e'
        webserver_image_name: webserver1
        webserver_version: 0.0.1
...