---
# tasks file for buildserver
- name: Ensure that docker and docker-compose installed
  apt:
    pkg:
      - default-jdk
      - maven
      - git
    update_cache: yes
    state: present

# - name: Login into docker hub
#   community.docker.docker_login:
#     username: "{{ dockerhub_username }}"
#     password: "{{ dockerhub_token }}"

# - name: Create build_server image
#   community.docker.docker_image:
#     build:
#       path: ~/
#       rm: yes
#       # pull: yes
#     name: "{{ build_server_name }}"
#     source: build
#     state: present
#     tag: "{{ build_server_version }}"
#     repository: "{{ [dockerhub_username, build_server_name] | join('/') }}"
#     push: yes
...